"""
12 персональных исключений для фармацевтической компании.
"""

class НедостаточноСредств(Exception): ...
class НеверныйПароль(Exception): ...
class КартаЗаблокирована(Exception): ...
class ТранзакцияОтклоненаАнтифродом(Exception): ...
class ПросроченнаяЛицензия(Exception): ...
class НеверныйИдентификаторПартии(Exception): ...
class ОшибкаСкладскогоУчёта(Exception): ...
class НарушениеТемпературногоРежима(Exception): ...
class НекорректныеПраваДоступа(Exception): ...
class ОшибкаОтчётности(Exception): ...
class ЗапретРегулятора(Exception): pass
class СертификатОтсутствует(Exception): pass
class ОграничениеАнтифрод(Exception): pass
